#!/bin/bash

exec > /tmp/internet-log 2>&1

set -x

echo 6000 > /proc/sys/fs/xfs/xfssyncd_centisecs
echo 6000 > /proc/sys/fs/xfs/filestream_centisecs
echo 1000 > /proc/sys/vm/dirty_writeback_centisecs
echo 4500 > /proc/sys/vm/dirty_expire_centisecs

chown -R speedyb0y:speedyb0y /dev/input/

GW_MAC1=90:55:de:a1:cd:f0
GW_MAC2=cc:ed:21:96:99:c0
GW_MAC3=54:9f:06:f4:c7:a0

LAN_NET=192.168.1.0/24

ME_IP=192.168.1.20
GW_IP1=192.168.1.1
GW_IP2=192.168.1.2
GW_IP3=192.168.1.3

CLOUDFLARE_ENDPOINT1=162.159.192.1
CLOUDFLARE_ENDPOINT2=162.159.192.1
CLOUDFLARE_ENDPOINT3=162.159.192.1

ip link set dev enp0s0 name eth0 ||
ip link set dev enp1s0 name eth0 ||
ip link set dev enp2s0 name eth0 ||
ip link set dev enp3s0 name eth0

ip link set dev eth0 mtu 9186
ip link set dev eth0 txqueuelen 8192

ethtool --offload eth0 rx off
ethtool --offload eth0 tx off
ethtool --offload eth0 tx-checksum-ip-generic off
ethtool --offload eth0 tx-checksum-ipv4 off
ethtool --offload eth0 tx-checksum-ipv6 off
ethtool --offload eth0 rx-vlan-offload off
ethtool --offload eth0 tx-vlan-offload off
ethtool --offload eth0 generic-segmentation-offload off
ethtool --offload eth0 generic-receive-offload off
ethtool --offload eth0 tcp-segmentation-offload off
ethtool --offload eth0 tx-tcp-segmentation off
ethtool --offload eth0 tx-tcp6-segmentation off

ethtool --pause eth0 autoneg off
ethtool --pause eth0 rx off
ethtool --pause eth0 tx off

# TODO: ISSO TEM QUE SER COLOCADO APOS FICAR UP?
#ethtool --coalesce eth0 rx-usecs 2000
#ethtool --coalesce eth0 tx-usecs 2000

echo 1200 65535 > /proc/sys/net/ipv4/ip_local_port_range
echo scalable > /proc/sys/net/ipv4/tcp_congestion_control

echo 120 > /proc/sys/net/ipv4/neigh/default/gc_interval
echo 120 > /proc/sys/net/ipv6/neigh/default/gc_interval

echo 60 > /proc/sys/net/ipv4/route/gc_interval
echo 60 > /proc/sys/net/ipv6/route/gc_interval

echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/drop_unsolicited_na

#
########echo 0 > /proc/sys/net/ipv4/conf/all/arp_accept # don't create new entries in the ARP table
echo 1 > /proc/sys/net/ipv4/conf/all/arp_announce
#######################################echo 1 > /proc/sys/net/ipv4/conf/all/arp_filter
#echo 8 > /proc/sys/net/ipv4/conf/all/arp_ignore # do not reply for all local addresses
#echo 0 > /proc/sys/net/ipv4/conf/all/arp_notify # do nothing
#echo 1 > /proc/sys/net/ipv4/conf/all/drop_gratuitous_arp

echo 1 > /proc/sys/net/ipv4/conf/eth0/arp_ignore # TODO: O MESMO COM O IPV6?
echo 1 > /proc/sys/net/ipv4/conf/eth0/arp_notify
echo 1 > /proc/sys/net/ipv4/conf/eth0/arp_accept
echo 0 > /proc/sys/net/ipv6/conf/eth0/autoconf
echo 0 > /proc/sys/net/ipv6/conf/eth0/accept_ra
echo 0 > /proc/sys/net/ipv6/conf/eth0/dad_transmits
echo 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6

ip link add dev dummy0 		 type dummy
ip link add dev cloudflare-1 type wireguard
ip link add dev cloudflare-2 type wireguard
ip link add dev cloudflare-3 type wireguard

echo 0 > /proc/sys/net/ipv6/conf/dummy0/autoconf
echo 0 > /proc/sys/net/ipv6/conf/cloudflare-1/autoconf
echo 0 > /proc/sys/net/ipv6/conf/cloudflare-2/autoconf
echo 0 > /proc/sys/net/ipv6/conf/cloudflare-3/autoconf

echo 0 > /proc/sys/net/ipv6/conf/dummy0/disable_ipv6
echo 0 > /proc/sys/net/ipv6/conf/cloudflare-1/disable_ipv6
echo 0 > /proc/sys/net/ipv6/conf/cloudflare-2/disable_ipv6
echo 0 > /proc/sys/net/ipv6/conf/cloudflare-3/disable_ipv6

# WIFI PRISCILA LAN
# 0c:80:63:a7:ef:3e
# 0c:80:63:a7:ef:3f INTERNAL
ip -4 neigh add nud permanent dev eth0 lladdr 50:d4:f7:48:c2:ee 192.168.1.5 # SWITCH
ip -4 neigh add nud permanent dev eth0 lladdr ${GW_MAC1} ${GW_IP1}
ip -4 neigh add nud permanent dev eth0 lladdr ${GW_MAC2} ${GW_IP2}
ip -4 neigh add nud permanent dev eth0 lladdr ${GW_MAC3} ${GW_IP3}

#########################################################

echo cN3zsnxJRuwAzNHtuZZnWQY/ABylb35SwfWLlXTvYXQ= | wg set cloudflare-1 \
    listen-port 5111 \
    private-key /proc/self/fd/0 \
    peer bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo= \
    endpoint ${CLOUDFLARE_ENDPOINT1}:2408 \
    allowed-ips 0.0.0.0/0,::0/0 \
    persistent-keepalive 5

echo mNyepvndy+VQStNsLctBeLIyyyfqlKW9FhGcrg8hPH4= | wg set cloudflare-2 \
    listen-port 5222 \
    private-key /proc/self/fd/0 \
    peer bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo= \
    endpoint ${CLOUDFLARE_ENDPOINT2}:2408 \
    allowed-ips 0.0.0.0/0,::0/0 \
    persistent-keepalive 5

echo +C2SFE9ty/NUBXCT8CXd7DcwQ4Qs0ZRrvrpBjJHo4GQ= | wg set cloudflare-3 \
    listen-port 5333 \
    private-key /proc/self/fd/0 \
    peer bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo= \
    endpoint ${CLOUDFLARE_ENDPOINT3}:2408 \
    allowed-ips 0.0.0.0/0,::0/0 \
    persistent-keepalive 5

ip link set mtu 1432 dev cloudflare-1 # 1440
ip link set mtu 1432 dev cloudflare-2
ip link set mtu 1432 dev cloudflare-3

#########################################################
if 0 ; then
# ADDRESSES
ip -4 addr add dev eth0 ${ME_IP}/24 noprefixroute

ip -4 addr add dev cloudflare-1 172.16.0.2
ip -4 addr add dev cloudflare-2 172.16.0.2
ip -4 addr add dev cloudflare-3 172.16.0.2

ip -6 addr add dev cloudflare-1 2606:4700:110:8b4d:dfb2:bd78:bed0:b941
ip -6 addr add dev cloudflare-2 2606:4700:110:8e7b:33e2:dc6c:04f7:92fb
ip -6 addr add dev cloudflare-3 2606:4700:110:89fa:2c24:6653:bfa6:84a4

# TO NETWORK
ip -4 route add table 1000 dev eth0 mtu lock 1500 advmss $[1500-40] src ${ME_IP} ${LAN_NET}
ip -4 route add table 1111 dev eth0 mtu lock 1492 advmss $[1492-40] src ${ME_IP} ${CLOUDFLARE_ENDPOINT1} via ${GW_IP1}
ip -4 route add table 1222 dev eth0 mtu lock 1500 advmss $[1500-40] src ${ME_IP} ${CLOUDFLARE_ENDPOINT2} via ${GW_IP2}
ip -4 route add table 1333 dev eth0 mtu lock 1500 advmss $[1500-40] src ${ME_IP} ${CLOUDFLARE_ENDPOINT3} via ${GW_IP3}
fi


ip link set dev cloudflare-isp up
ip link set dev cloudflare up
ip link set up dev cloudflare-1
ip link set up dev cloudflare-2
ip link set up dev cloudflare-3
ip link set up dev eth0

ip -4 addr add dev eth0 192.168.1.20/24 noprefixroute
ip -4 addr add dev eth0 192.168.1.25/24

ip -4 addr add dev cloudflare   172.16.0.2
ip -4 addr add dev cloudflare-1 172.16.0.2
ip -4 addr add dev cloudflare-2 172.16.0.2
ip -4 addr add dev cloudflare-3 172.16.0.2

ip -4 addr add dev cloudflare-isp 192.168.1.25

ip -4 route add metric 1 dev eth0 192.168.1.0/24 src 192.168.1.20
ip -4 route add metric 1 dev cloudflare-isp 162.159.192.1 src 192.168.1.25
ip -4 route add metric 2 unreachable 162.159.192.1
ip -4 route add metric 1 dev cloudflare mtu 1432 advmss $[1420-40] src 172.16.0.2 default # TODO: ADVMSS 1360?
ip -6 route add metric 1 dev cloudflare mtu 1432 advmss $[1420-60] src 2606:4700:110:8b4d:dfb2:bd78:bed0:b941 default

ip -4 route flush cache
ip -6 route flush cache
