#!/bin/bash

TABLE_XSOCK=5

(make && insmod xsock-clt.ko)

echo scalable > /proc/sys/net/ipv4/tcp_congestion_control
echo 4096 > /proc/sys/net/ipv4/tcp_max_reordering
echo  300 > /proc/sys/net/ipv4/tcp_reordering


###
for ITFC in eth0 enp1s0 enp6s0 enp5s0 ; do
    ethtool --offload ${ITFC} rx off
    ethtool --offload ${ITFC} tx off
    ethtool --offload ${ITFC} tx-checksum-ip-generic off
    ethtool --offload ${ITFC} tx-checksum-ipv4 off
    ethtool --offload ${ITFC} tx-checksum-ipv6 off
    ethtool --offload ${ITFC} rx-vlan-offload off
    ethtool --offload ${ITFC} tx-vlan-offload off
    ethtool --offload ${ITFC} generic-segmentation-offload off
    ethtool --offload ${ITFC} generic-receive-offload off
    ethtool --offload ${ITFC} tcp-segmentation-offload off
    ethtool --offload ${ITFC} tx-tcp-segmentation off
    ethtool --offload ${ITFC} tx-tcp6-segmentation off
    ethtool --pause ${ITFC} autoneg off
    ethtool --pause ${ITFC} rx off
    ethtool --pause ${ITFC} tx off
done
###

echo 1 > /proc/sys/net/ipv6/conf/enp5s0/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/enp6s0/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/xsock/disable_ipv6

ip link set dev xsock up

ISP_MTU=1472

ip -4 rule add priority 10 table ${TABLE_XSOCK} to 172.16.0.0
ip -4 rule add priority 10 table ${TABLE_XSOCK} from 172.16.0.1
ip -4 rule add priority 10 table ${TABLE_XSOCK} oif xsock
ip -4 addr add dev xsock 172.16.0.1
#rttvar TIME (Linux 2.3.15+ only)
#ssthresh NUMBER (Linux 2.3.15+ only)
ip -4 route add table ${TABLE_XSOCK} dev xsock mtu ${ISP_MTU} advmss $[${ISP_MTU}-40] src 172.16.0.1 172.16.0.0 rtt 210ms rto_min 400ms
ip -4 route flush cache
