#!/bin/bash

ISP_MTU=1472

(make && insmod xsock-srv.ko)

#echo scalable > /proc/sys/net/ipv4/tcp_congestion_control
echo 4096 > /proc/sys/net/ipv4/tcp_max_reordering
echo 300 > /proc/sys/net/ipv4/tcp_reordering
echo 1 > /proc/sys/net/ipv6/conf/xsock/disable_ipv6
#echo 1 > /proc/sys/net/ipv4/tcp_fwmark_accept

ip link set dev xsock up

ip -4 addr add dev xsock 172.16.0.0
ip -4 route add dev xsock mtu ${ISP_MTU} advmss $[${ISP_MTU}-40] src 172.16.0.0 172.16.0.1 rtt 210ms rto_min 400ms
